services:
  kv1:
    build: .
    container_name: kv1
    environment:
      NODE_NAME: kv1
      PORT: "3000"
      PARTICIPANTS: "http://kv2:3000,http://kv3:3000"
    ports:
      - "3001:3000"
    networks:
      - kvnet

  kv2:
    build: .
    container_name: kv2
    environment:
      NODE_NAME: kv2
      PORT: "3000"
      PARTICIPANTS: "http://kv1:3000,http://kv3:3000"
    ports:
      - "3002:3000"
    networks:
      - kvnet

  kv3:
    build: .
    container_name: kv3
    environment:
      NODE_NAME: kv3
      PORT: "3000"
      PARTICIPANTS: "http://kv1:3000,http://kv2:3000"
    ports:
      - "3003:3000"
    networks:
      - kvnet

networks:
  kvnet:
